/* ============================================================
   FOOD DATABASE — ingredient-list.js
   ============================================================
   WHAT THIS FILE IS:
   Just data — the list of food categories, every ingredient
   (name + calories/protein/carbs/fat/fiber/sugar per 100g or
   per piece), the emoji icons used for meals, and the emoji
   icons offered when creating a category. There is no page
   logic in this file at all.

   WHO USES THIS DATA:
   Every other file in this app reads from the CATEGORIES,
   CATEGORY_MAP, CATEGORY_TINTS, INGREDIENTS, MEAL_ICONS and
   CAT_ICON_OPTIONS
   variables below (they're defined with "let"/"const" so they
   become available to every other script on the page once this
   file has loaded — index.html loads this file first, before
   any other script, for that reason).

   SAFE TO REWORK ALONE?
   Yes — if you just want to add/edit/remove foods or categories,
   this file is fully self-contained. Don't rename the variables
   CATEGORIES, CATEGORY_MAP, CATEGORY_TINTS, INGREDIENTS,
   MEAL_ICONS or CAT_ICON_OPTIONS, and keep each ingredient object using the
   same field names (name, kcal, protein, carbs, fat, fiber,
   sugar, category, and optionally unit) — other files depend on
   those exact field names.
   ============================================================ */

let CATEGORIES = [
    { name: 'Meat', icon: '🥩' },
    { name: 'Fish & Seafood', icon: '🐟' },
    { name: 'Eggs', icon: '🥚' },
    { name: 'Dairy', icon: '🧀' },
    { name: 'Breads', icon: '🍞' },
    { name: 'Flours & Grains', icon: '🌾' },
    { name: 'Fruits', icon: '🍎' },
    { name: 'Nuts & Seeds', icon: '🥜' },
    { name: 'Vegetables', icon: '🥬' },
    { name: 'Oils & Fats', icon: '🧈' },
    { name: 'Condiments', icon: '🧂' },
    { name: 'Sweeteners & Spices', icon: '🍯' },
    { name: 'ICA Specific', icon: '🛒' },
    { name: 'Beverages', icon: '🥤' },
    { name: 'Other', icon: '📦' }
];

let CATEGORY_MAP = {};
CATEGORIES.forEach(c => CATEGORY_MAP[c.name] = c);

/* Tile colour for each category's icon (the soft square behind the emoji —
   see .cat-icon in shared/theme-and-layout.css and categoryTint() in
   shared/app-data-and-settings.js).

   Keyed by NAME rather than stored on the category objects on purpose:
   CATEGORIES gets overwritten by whatever is in localStorage when a user has
   edited their categories, so a field added to the objects here would never
   reach anyone who already has saved ones. Looking the colour up by name
   works for existing users and new ones alike, and any category NOT listed
   here (i.e. one the user made themselves) gets a colour derived from its
   name instead. */
const CATEGORY_TINTS = {
    'Meat': '#e74c3c',
    'Fish & Seafood': '#3aa6d8',
    'Eggs': '#f1c40f',
    'Dairy': '#f39c12',
    'Breads': '#c8893a',
    'Flours & Grains': '#b8963f',
    'Fruits': '#e0516b',
    'Nuts & Seeds': '#a9714b',
    'Vegetables': '#2ecc71',
    'Oils & Fats': '#8fa83f',
    'Condiments': '#8e9aa8',
    'Sweeteners & Spices': '#e8a33d',
    'ICA Specific': '#e4572e',
    'Beverages': '#9b59b6',
    'Other': '#6b7f94'
};

let INGREDIENTS = [
    { name: 'Beef, raw', kcal: 250, protein: 26, carbs: 0, fat: 16, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Beef, boiled', kcal: 280, protein: 28, carbs: 0, fat: 18, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Beef, roasted', kcal: 310, protein: 27, carbs: 0, fat: 22, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Beef mince (10%)', kcal: 176, protein: 20, carbs: 0, fat: 10, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Beef mince (20%)', kcal: 254, protein: 19, carbs: 0, fat: 20, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Veal, raw', kcal: 150, protein: 22, carbs: 0, fat: 6, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Veal, boiled', kcal: 190, protein: 26, carbs: 0, fat: 9, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Pork, raw', kcal: 242, protein: 27, carbs: 0, fat: 14, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Pork, roasted', kcal: 270, protein: 26, carbs: 0, fat: 18, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Pork chop', kcal: 242, protein: 27, carbs: 0, fat: 14, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Pork tenderloin', kcal: 143, protein: 22, carbs: 0, fat: 5, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Lamb, raw', kcal: 294, protein: 25, carbs: 0, fat: 21, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Lamb, roasted', kcal: 320, protein: 25, carbs: 0, fat: 24, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Chicken breast, raw', kcal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0,
    category: 'Meat' },
    { name: 'Chicken breast, boiled', kcal: 175, protein: 33, carbs: 0, fat: 4, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Chicken breast, roasted', kcal: 190, protein: 32, carbs: 0, fat: 6, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Chicken thigh, raw', kcal: 209, protein: 26, carbs: 0, fat: 11, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Chicken thigh, roasted', kcal: 230, protein: 25, carbs: 0, fat: 14, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Chicken drumstick', kcal: 172, protein: 28, carbs: 0, fat: 6, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Chicken wing', kcal: 203, protein: 23, carbs: 0, fat: 12, fiber: 0, sugar: 0, category: 'Meat' },
    { name: 'Turkey breast, raw', kcal: 135, protein: 30, carbs: 0, fat: 1.5, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Turkey breast, roasted', kcal: 150, protein: 31, carbs: 0, fat: 2.5, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Duck breast, raw', kcal: 200, protein: 23, carbs: 0, fat: 12, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Duck breast, roasted', kcal: 230, protein: 22, carbs: 0, fat: 16, fiber: 0, sugar: 0,
        category: 'Meat' },
    { name: 'Salmon, raw', kcal: 208, protein: 22, carbs: 0, fat: 13, fiber: 0, sugar: 0,
    category: 'Fish & Seafood' },
    { name: 'Salmon, boiled', kcal: 210, protein: 24, carbs: 0, fat: 12, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Salmon, fried', kcal: 240, protein: 23, carbs: 0, fat: 16, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Salmon, smoked', kcal: 210, protein: 23, carbs: 0, fat: 13, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Cod, raw', kcal: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, sugar: 0,
    category: 'Fish & Seafood' },
    { name: 'Cod, boiled', kcal: 85, protein: 19, carbs: 0, fat: 0.8, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Cod, fried', kcal: 110, protein: 18, carbs: 0, fat: 4, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Herring, raw', kcal: 158, protein: 18, carbs: 0, fat: 9, fiber: 0, sugar: 0,
    category: 'Fish & Seafood' },
    { name: 'Herring, pickled', kcal: 190, protein: 16, carbs: 5, fat: 11, fiber: 0, sugar: 5,
        category: 'Fish & Seafood' },
    { name: 'Mackerel, raw', kcal: 205, protein: 19, carbs: 0, fat: 14, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Mackerel, smoked', kcal: 220, protein: 20, carbs: 0, fat: 15, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Tuna, canned water', kcal: 116, protein: 26, carbs: 0, fat: 1, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Tuna, canned oil', kcal: 200, protein: 25, carbs: 0, fat: 10, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Shrimp, raw', kcal: 85, protein: 18, carbs: 0, fat: 1, fiber: 0, sugar: 0,
    category: 'Fish & Seafood' },
    { name: 'Shrimp, boiled', kcal: 90, protein: 19, carbs: 0, fat: 1.2, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Mussels, raw', kcal: 86, protein: 12, carbs: 3.7, fat: 2.2, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Mussels, boiled', kcal: 90, protein: 13, carbs: 4, fat: 2.3, fiber: 0, sugar: 0,
        category: 'Fish & Seafood' },
    { name: 'Egg, raw (pc)', kcal: 72, protein: 6.3, carbs: 0.4, fat: 5, fiber: 0, sugar: 0.4, unit: 'pc',
        category: 'Eggs' },
    { name: 'Egg, boiled (pc)', kcal: 78, protein: 6.5, carbs: 0.5, fat: 5.3, fiber: 0, sugar: 0.5, unit: 'pc',
        category: 'Eggs' },
    { name: 'Egg, fried (pc)', kcal: 90, protein: 6.5, carbs: 0.5, fat: 7, fiber: 0, sugar: 0.5, unit: 'pc',
        category: 'Eggs' },
    { name: 'Egg white (pc)', kcal: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0, sugar: 0.2, unit: 'pc',
        category: 'Eggs' },
    { name: 'Egg yolk (pc)', kcal: 55, protein: 2.7, carbs: 0.6, fat: 4.8, fiber: 0, sugar: 0.6, unit: 'pc',
        category: 'Eggs' },
    { name: 'Milk (3%)', kcal: 64, protein: 3.3, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 4.8, category: 'Dairy' },
    { name: 'Milk (1.5%)', kcal: 47, protein: 3.4, carbs: 4.8, fat: 1.5, fiber: 0, sugar: 4.8, category: 'Dairy' },
    { name: 'Milk (skim)', kcal: 34, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, sugar: 5, category: 'Dairy' },
    { name: 'Yogurt, plain (3%)', kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, fiber: 0, sugar: 4.7,
        category: 'Dairy' },
    { name: 'Yogurt, plain (0.1%)', kcal: 40, protein: 3.8, carbs: 5, fat: 0.1, fiber: 0, sugar: 5,
        category: 'Dairy' },
    { name: 'Greek yogurt (10%)', kcal: 120, protein: 5, carbs: 4, fat: 10, fiber: 0, sugar: 4,
        category: 'Dairy' },
    { name: 'Greek yogurt (0%)', kcal: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, sugar: 3.6,
        category: 'Dairy' },
    { name: 'Skyr (ICA)', kcal: 60, protein: 9, carbs: 4, fat: 0.2, fiber: 0, sugar: 4, category: 'Dairy' },
    { name: 'Kvarg (ICA)', kcal: 55, protein: 10, carbs: 3.5, fat: 0.2, fiber: 0, sugar: 3.5,
    category: 'Dairy' },
    { name: 'Cream (40%)', kcal: 345, protein: 2.5, carbs: 3, fat: 37, fiber: 0, sugar: 3, category: 'Dairy' },
    { name: 'Cream (15%)', kcal: 150, protein: 2.5, carbs: 4, fat: 15, fiber: 0, sugar: 4, category: 'Dairy' },
    { name: 'Sour cream (25%)', kcal: 198, protein: 2.4, carbs: 4.3, fat: 19, fiber: 0, sugar: 4.3,
        category: 'Dairy' },
    { name: 'Cottage cheese (4%)', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, fiber: 0, sugar: 3.4,
        category: 'Dairy' },
    { name: 'Cottage cheese (0.5%)', kcal: 72, protein: 12, carbs: 3.5, fat: 0.5, fiber: 0, sugar: 3.5,
        category: 'Dairy' },
    { name: 'Cheese, hard (28%)', kcal: 402, protein: 25, carbs: 1.3, fat: 33, fiber: 0, sugar: 1.3,
        category: 'Dairy' },
    { name: 'Cheese, semi-hard (17%)', kcal: 300, protein: 24, carbs: 2, fat: 22, fiber: 0, sugar: 2,
        category: 'Dairy' },
    { name: 'Cheese, soft (20%)', kcal: 300, protein: 18, carbs: 2, fat: 25, fiber: 0, sugar: 2,
        category: 'Dairy' },
    { name: 'Cream cheese', kcal: 340, protein: 6, carbs: 4, fat: 34, fiber: 0, sugar: 4, category: 'Dairy' },
    { name: 'Parmesan', kcal: 431, protein: 38, carbs: 4, fat: 29, fiber: 0, sugar: 4, category: 'Dairy' },
    { name: 'Feta cheese', kcal: 264, protein: 14, carbs: 4, fat: 21, fiber: 0, sugar: 4, category: 'Dairy' },
    { name: 'Bread, rye (ICA)', kcal: 250, protein: 10, carbs: 42, fat: 3, fiber: 6, sugar: 2,
    category: 'Breads' },
    { name: 'Bread, sourdough', kcal: 260, protein: 9, carbs: 48, fat: 2.5, fiber: 4, sugar: 3,
        category: 'Breads' },
    { name: 'Bread, white', kcal: 265, protein: 8, carbs: 49, fat: 2, fiber: 2, sugar: 4, category: 'Breads' },
    { name: 'Bread, whole grain', kcal: 250, protein: 10, carbs: 42, fat: 3, fiber: 6, sugar: 2,
        category: 'Breads' },
    { name: 'Bread, crisp (knäckebröd)', kcal: 350, protein: 10, carbs: 70, fat: 3, fiber: 15, sugar: 1,
        category: 'Breads' },
    { name: 'Baguette', kcal: 280, protein: 9, carbs: 52, fat: 2, fiber: 3, sugar: 2, category: 'Breads' },
    { name: 'Ciabatta', kcal: 270, protein: 9, carbs: 50, fat: 3, fiber: 3, sugar: 2, category: 'Breads' },
    { name: 'Pita bread', kcal: 275, protein: 9, carbs: 55, fat: 1.5, fiber: 3, sugar: 2, category: 'Breads' },
    { name: 'Tortilla wrap', kcal: 300, protein: 8, carbs: 50, fat: 8, fiber: 4, sugar: 3,
    category: 'Breads' },
    { name: 'Flour, wheat (white)', kcal: 364, protein: 10, carbs: 76, fat: 1, fiber: 2.7, sugar: 0.4,
        category: 'Flours & Grains' },
    { name: 'Flour, wheat (whole)', kcal: 340, protein: 13, carbs: 72, fat: 2.5, fiber: 10.7, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Flour, rye', kcal: 350, protein: 10, carbs: 70, fat: 2, fiber: 14, sugar: 1,
    category: 'Flours & Grains' },
    { name: 'Flour, oat', kcal: 380, protein: 15, carbs: 65, fat: 7, fiber: 10, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Flour, almond', kcal: 580, protein: 22, carbs: 20, fat: 50, fiber: 12, sugar: 5,
        category: 'Flours & Grains' },
    { name: 'Flour, coconut', kcal: 440, protein: 19, carbs: 28, fat: 18, fiber: 39, sugar: 8,
        category: 'Flours & Grains' },
    { name: 'Oatmeal (rolled oats)', kcal: 389, protein: 17, carbs: 66, fat: 7, fiber: 10, sugar: 1,
        category: 'Flours & Grains' },
    { name: 'Rice, white (raw)', kcal: 360, protein: 7, carbs: 78, fat: 0.6, fiber: 0.8, sugar: 0.1,
        category: 'Flours & Grains' },
    { name: 'Rice, white (boiled)', kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0.1,
        category: 'Flours & Grains' },
    { name: 'Rice, brown (raw)', kcal: 350, protein: 8, carbs: 74, fat: 2.5, fiber: 3.5, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Rice, brown (boiled)', kcal: 123, protein: 2.7, carbs: 26, fat: 0.9, fiber: 1.8, sugar: 0.2,
        category: 'Flours & Grains' },
    { name: 'Rice, wild (raw)', kcal: 360, protein: 14, carbs: 72, fat: 1.5, fiber: 6, sugar: 1,
        category: 'Flours & Grains' },
    { name: 'Rice, wild (boiled)', kcal: 100, protein: 4, carbs: 21, fat: 0.5, fiber: 2, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Pasta, dry', kcal: 365, protein: 13, carbs: 72, fat: 1.5, fiber: 3, sugar: 1,
    category: 'Flours & Grains' },
    { name: 'Pasta, boiled', kcal: 131, protein: 5, carbs: 25, fat: 0.6, fiber: 1.5, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Couscous, dry', kcal: 370, protein: 13, carbs: 76, fat: 1, fiber: 5, sugar: 1,
        category: 'Flours & Grains' },
    { name: 'Couscous, boiled', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, sugar: 0.3,
        category: 'Flours & Grains' },
    { name: 'Quinoa, raw', kcal: 370, protein: 14, carbs: 64, fat: 6, fiber: 7, sugar: 1,
    category: 'Flours & Grains' },
    { name: 'Quinoa, boiled', kcal: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, sugar: 0.5,
        category: 'Flours & Grains' },
    { name: 'Apple', kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sugar: 10, category: 'Fruits' },
    { name: 'Banana', kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12, category: 'Fruits' },
    { name: 'Orange', kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sugar: 9, category: 'Fruits' },
    { name: 'Pear', kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, sugar: 10, category: 'Fruits' },
    { name: 'Grapes', kcal: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, sugar: 16, category: 'Fruits' },
    { name: 'Strawberries', kcal: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, sugar: 5, category: 'Fruits' },
    { name: 'Blueberries', kcal: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, sugar: 10,
        category: 'Fruits' },
    { name: 'Raspberries', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7, fiber: 6.5, sugar: 4,
        category: 'Fruits' },
    { name: 'Blackberries', kcal: 43, protein: 1.4, carbs: 10, fat: 0.5, fiber: 5.3, sugar: 5,
        category: 'Fruits' },
    { name: 'Cherries', kcal: 50, protein: 1, carbs: 12, fat: 0.3, fiber: 1.6, sugar: 8, category: 'Fruits' },
    { name: 'Peach', kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, fiber: 1.5, sugar: 8, category: 'Fruits' },
    { name: 'Plum', kcal: 46, protein: 0.7, carbs: 11, fat: 0.3, fiber: 1.4, sugar: 9, category: 'Fruits' },
    { name: 'Kiwi', kcal: 61, protein: 1, carbs: 15, fat: 0.5, fiber: 3, sugar: 9, category: 'Fruits' },
    { name: 'Mango', kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 14, category: 'Fruits' },
    { name: 'Pineapple', kcal: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, sugar: 10,
    category: 'Fruits' },
    { name: 'Watermelon', kcal: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, sugar: 6,
    category: 'Fruits' },
    { name: 'Dates, dried', kcal: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8, sugar: 63,
    category: 'Fruits' },
    { name: 'Raisins', kcal: 299, protein: 3, carbs: 79, fat: 0.5, fiber: 3.7, sugar: 59, category: 'Fruits' },
    { name: 'Prunes', kcal: 240, protein: 2.2, carbs: 64, fat: 0.4, fiber: 7, sugar: 38, category: 'Fruits' },
    { name: 'Apricots, dried', kcal: 241, protein: 3.4, carbs: 63, fat: 0.5, fiber: 7.3, sugar: 53,
        category: 'Fruits' },
    { name: 'Figs, dried', kcal: 249, protein: 3.3, carbs: 64, fat: 0.9, fiber: 9.8, sugar: 47,
        category: 'Fruits' },
    { name: 'Lingonberries, raw', kcal: 50, protein: 0.4, carbs: 12.0, fat: 0.3, fiber: 3.5, sugar: 6.0,
        category: 'Fruits' },
    { name: 'Cloudberries, raw', kcal: 51, protein: 2.4, carbs: 8.6, fat: 0.8, fiber: 6.3, sugar: 4.0,
        category: 'Fruits' },
    { name: 'Blackcurrants, raw', kcal: 63, protein: 1.4, carbs: 15.4, fat: 0.4, fiber: 4.3, sugar: 8.0,
        category: 'Fruits' },
    { name: 'Redcurrants, raw', kcal: 56, protein: 1.4, carbs: 13.8, fat: 0.2, fiber: 4.3, sugar: 7.4,
        category: 'Fruits' },
    { name: 'Gooseberries, raw', kcal: 44, protein: 0.9, carbs: 10.2, fat: 0.6, fiber: 4.3, sugar: 8.0,
        category: 'Fruits' },
    { name: 'Rhubarb, raw', kcal: 21, protein: 0.9, carbs: 4.5, fat: 0.2, fiber: 1.8, sugar: 1.1,
        category: 'Fruits' },
    { name: 'Cranberries, raw', kcal: 46, protein: 0.4, carbs: 12.2, fat: 0.1, fiber: 4.6, sugar: 4.0,
        category: 'Fruits' },
    { name: 'Cranberries, dried', kcal: 308, protein: 0.1, carbs: 82.4, fat: 1.4, fiber: 5.7, sugar: 65.0,
        category: 'Fruits' },
    { name: 'Sour cherries, raw', kcal: 50, protein: 1.0, carbs: 12.2, fat: 0.3, fiber: 1.6, sugar: 8.5,
        category: 'Fruits' },
    { name: 'Melon, cantaloupe', kcal: 34, protein: 0.8, carbs: 8.2, fat: 0.2, fiber: 0.9, sugar: 7.9,
        category: 'Fruits' },
    { name: 'Melon, honeydew', kcal: 36, protein: 0.5, carbs: 9.1, fat: 0.1, fiber: 0.8, sugar: 8.1,
        category: 'Fruits' },
    { name: 'Nectarine', kcal: 44, protein: 1.1, carbs: 10.6, fat: 0.3, fiber: 1.7, sugar: 7.9,
        category: 'Fruits' },
    { name: 'Apricot, fresh', kcal: 48, protein: 1.4, carbs: 11.1, fat: 0.4, fiber: 2.0, sugar: 9.2,
        category: 'Fruits' },
    { name: 'Grapefruit', kcal: 42, protein: 0.8, carbs: 10.7, fat: 0.1, fiber: 1.6, sugar: 6.9,
        category: 'Fruits' },
    { name: 'Lemon', kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, sugar: 2.5,
        category: 'Fruits' },
    { name: 'Lime', kcal: 30, protein: 0.7, carbs: 10.5, fat: 0.2, fiber: 2.8, sugar: 1.7,
        category: 'Fruits' },
    { name: 'Clementine', kcal: 47, protein: 0.9, carbs: 12.0, fat: 0.2, fiber: 1.7, sugar: 9.2,
        category: 'Fruits' },
    { name: 'Mandarin', kcal: 53, protein: 0.8, carbs: 13.3, fat: 0.3, fiber: 1.8, sugar: 10.6,
        category: 'Fruits' },
    { name: 'Papaya', kcal: 43, protein: 0.5, carbs: 10.8, fat: 0.3, fiber: 1.7, sugar: 7.8,
        category: 'Fruits' },
    { name: 'Pomegranate', kcal: 83, protein: 1.7, carbs: 18.7, fat: 1.2, fiber: 4.0, sugar: 13.7,
        category: 'Fruits' },
    { name: 'Passion fruit', kcal: 97, protein: 2.2, carbs: 23.4, fat: 0.7, fiber: 10.4, sugar: 11.2,
        category: 'Fruits' },
    { name: 'Persimmon', kcal: 70, protein: 0.6, carbs: 18.6, fat: 0.2, fiber: 3.6, sugar: 12.5,
        category: 'Fruits' },
    { name: 'Guava', kcal: 68, protein: 2.6, carbs: 14.3, fat: 1.0, fiber: 5.4, sugar: 8.9,
        category: 'Fruits' },
    { name: 'Lychee', kcal: 66, protein: 0.8, carbs: 16.5, fat: 0.4, fiber: 1.3, sugar: 15.2,
        category: 'Fruits' },
    { name: 'Coconut, fresh', kcal: 354, protein: 3.3, carbs: 15.2, fat: 33.5, fiber: 9.0, sugar: 6.2,
        category: 'Fruits' },
    { name: 'Banana, dried', kcal: 346, protein: 3.9, carbs: 88.3, fat: 1.8, fiber: 9.9, sugar: 47.3,
        category: 'Fruits' },
    { name: 'Blueberries, frozen', kcal: 51, protein: 0.4, carbs: 12.2, fat: 0.6, fiber: 3.4, sugar: 8.5,
        category: 'Fruits' },
    { name: 'Raspberries, frozen', kcal: 52, protein: 1.2, carbs: 11.9, fat: 0.7, fiber: 6.5, sugar: 4.4,
        category: 'Fruits' },
    { name: 'Plantain, raw', kcal: 122, protein: 1.3, carbs: 31.9, fat: 0.4, fiber: 2.3, sugar: 15.0,
        category: 'Fruits' },
    { name: 'Almonds', kcal: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, sugar: 4,
    category: 'Nuts & Seeds' },
    { name: 'Walnuts', kcal: 654, protein: 15, carbs: 14, fat: 65, fiber: 7, sugar: 3,
    category: 'Nuts & Seeds' },
    { name: 'Peanuts, roasted', kcal: 567, protein: 26, carbs: 16, fat: 49, fiber: 8.5, sugar: 4,
        category: 'Nuts & Seeds' },
    { name: 'Cashews', kcal: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, sugar: 6,
    category: 'Nuts & Seeds' },
    { name: 'Pistachios', kcal: 560, protein: 20, carbs: 28, fat: 45, fiber: 10, sugar: 8,
    category: 'Nuts & Seeds' },
    { name: 'Sunflower seeds', kcal: 584, protein: 21, carbs: 20, fat: 51, fiber: 8.6, sugar: 3,
        category: 'Nuts & Seeds' },
    { name: 'Pumpkin seeds', kcal: 446, protein: 19, carbs: 18, fat: 19, fiber: 6.5, sugar: 1,
        category: 'Nuts & Seeds' },
    { name: 'Chia seeds', kcal: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, sugar: 1,
    category: 'Nuts & Seeds' },
    { name: 'Flax seeds', kcal: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, sugar: 2,
    category: 'Nuts & Seeds' },
    { name: 'Sesame seeds', kcal: 573, protein: 18, carbs: 23, fat: 50, fiber: 12, sugar: 0.3,
        category: 'Nuts & Seeds' },
    { name: 'Hemp seeds', kcal: 553, protein: 31, carbs: 9, fat: 49, fiber: 4, sugar: 2,
    category: 'Nuts & Seeds' },
    { name: 'Potato, raw', kcal: 77, protein: 2, carbs: 17, fat: 0.1, fiber: 2.2, sugar: 0.8,
    category: 'Vegetables' },
    { name: 'Potato, boiled', kcal: 82, protein: 2.1, carbs: 18, fat: 0.1, fiber: 2.2, sugar: 0.8,
        category: 'Vegetables' },
    { name: 'Potato, roasted', kcal: 150, protein: 2.2, carbs: 24, fat: 5, fiber: 2.5, sugar: 1.5,
        category: 'Vegetables' },
    { name: 'Sweet potato, raw', kcal: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, sugar: 4.2,
        category: 'Vegetables' },
    { name: 'Sweet potato, boiled', kcal: 90, protein: 1.7, carbs: 21, fat: 0.1, fiber: 3, sugar: 4.5,
        category: 'Vegetables' },
    { name: 'Carrot, raw', kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7,
        category: 'Vegetables' },
    { name: 'Carrot, boiled', kcal: 35, protein: 0.8, carbs: 8, fat: 0.2, fiber: 2.5, sugar: 4,
        category: 'Vegetables' },
    { name: 'Broccoli, raw', kcal: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, sugar: 1.7,
        category: 'Vegetables' },
    { name: 'Broccoli, boiled', kcal: 35, protein: 2.9, carbs: 7.5, fat: 0.4, fiber: 2.6, sugar: 1.7,
        category: 'Vegetables' },
    { name: 'Cauliflower, raw', kcal: 25, protein: 2, carbs: 5, fat: 0.3, fiber: 2, sugar: 1.9,
        category: 'Vegetables' },
    { name: 'Cauliflower, boiled', kcal: 23, protein: 1.8, carbs: 4.5, fat: 0.3, fiber: 2, sugar: 1.7,
        category: 'Vegetables' },
    { name: 'Spinach, raw', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4,
        category: 'Vegetables' },
    { name: 'Spinach, boiled', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4,
        category: 'Vegetables' },
    { name: 'Tomato, raw', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6,
        category: 'Vegetables' },
    { name: 'Cucumber', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7,
        category: 'Vegetables' },
    { name: 'Onion, raw', kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, sugar: 4.2,
        category: 'Vegetables' },
    { name: 'Onion, fried', kcal: 110, protein: 1.5, carbs: 12, fat: 6, fiber: 2, sugar: 5,
        category: 'Vegetables' },
    { name: 'Garlic', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, sugar: 1,
    category: 'Vegetables' },
    { name: 'Pepper, bell', kcal: 26, protein: 1, carbs: 6, fat: 0.3, fiber: 1.5, sugar: 4.2,
        category: 'Vegetables' },
    { name: 'Mushroom, raw', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2.5,
        category: 'Vegetables' },
    { name: 'Mushroom, fried', kcal: 70, protein: 3.2, carbs: 4, fat: 5, fiber: 1.2, sugar: 2,
        category: 'Vegetables' },
    { name: 'Avocado', kcal: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, sugar: 0.7, category: 'Vegetables' },
    { name: 'Lentils, dry', kcal: 350, protein: 25, carbs: 60, fat: 1.5, fiber: 30, sugar: 2,
        category: 'Vegetables' },
    { name: 'Lentils, boiled', kcal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, sugar: 1.8,
        category: 'Vegetables' },
    { name: 'Chickpeas, dry', kcal: 380, protein: 20, carbs: 63, fat: 6, fiber: 17, sugar: 10,
        category: 'Vegetables' },
    { name: 'Chickpeas, boiled', kcal: 139, protein: 8.9, carbs: 23, fat: 2.4, fiber: 7.6, sugar: 4.8,
        category: 'Vegetables' },
    { name: 'Kidney beans, dry', kcal: 340, protein: 22, carbs: 62, fat: 1.5, fiber: 25, sugar: 2.5,
        category: 'Vegetables' },
    { name: 'Kidney beans, boiled', kcal: 127, protein: 8.7, carbs: 23, fat: 0.5, fiber: 7.4, sugar: 0.3,
        category: 'Vegetables' },
    { name: 'Peas, frozen', kcal: 80, protein: 5, carbs: 15, fat: 0.4, fiber: 5, sugar: 5.6,
        category: 'Vegetables' },
    { name: 'Peas, boiled', kcal: 80, protein: 5, carbs: 15, fat: 0.4, fiber: 5, sugar: 5.6,
        category: 'Vegetables' },
    { name: 'Corn, canned', kcal: 86, protein: 3, carbs: 19, fat: 1.2, fiber: 2.5, sugar: 3.2,
        category: 'Vegetables' },
    { name: 'Zucchini, raw', kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1.0, sugar: 2.5,
        category: 'Vegetables' },
    { name: 'Aubergine, raw', kcal: 25, protein: 1.0, carbs: 5.9, fat: 0.2, fiber: 3.0, sugar: 3.5,
        category: 'Vegetables' },
    { name: 'Cabbage, white, raw', kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1, fiber: 2.5, sugar: 3.2,
        category: 'Vegetables' },
    { name: 'Cabbage, red, raw', kcal: 31, protein: 1.4, carbs: 7.4, fat: 0.2, fiber: 2.1, sugar: 3.8,
        category: 'Vegetables' },
    { name: 'Kale, raw', kcal: 49, protein: 4.3, carbs: 8.8, fat: 0.9, fiber: 3.6, sugar: 2.3,
        category: 'Vegetables' },
    { name: 'Brussels sprouts, raw', kcal: 43, protein: 3.4, carbs: 9.0, fat: 0.3, fiber: 3.8, sugar: 2.2,
        category: 'Vegetables' },
    { name: 'Brussels sprouts, boiled', kcal: 36, protein: 2.6, carbs: 7.1, fat: 0.5, fiber: 2.6, sugar: 1.7,
        category: 'Vegetables' },
    { name: 'Leek, raw', kcal: 61, protein: 1.5, carbs: 14.2, fat: 0.3, fiber: 1.8, sugar: 3.9,
        category: 'Vegetables' },
    { name: 'Celery, raw', kcal: 16, protein: 0.7, carbs: 3.0, fat: 0.2, fiber: 1.6, sugar: 1.3,
        category: 'Vegetables' },
    { name: 'Swede (kålrot), raw', kcal: 37, protein: 1.1, carbs: 8.6, fat: 0.2, fiber: 2.3, sugar: 4.5,
        category: 'Vegetables' },
    { name: 'Beetroot, raw', kcal: 43, protein: 1.6, carbs: 9.6, fat: 0.2, fiber: 2.8, sugar: 6.8,
        category: 'Vegetables' },
    { name: 'Beetroot, boiled', kcal: 44, protein: 1.7, carbs: 10.0, fat: 0.2, fiber: 2.0, sugar: 8.0,
        category: 'Vegetables' },
    { name: 'Parsnip, raw', kcal: 75, protein: 1.2, carbs: 18.0, fat: 0.3, fiber: 4.9, sugar: 4.8,
        category: 'Vegetables' },
    { name: 'Asparagus, raw', kcal: 20, protein: 2.2, carbs: 3.9, fat: 0.1, fiber: 2.1, sugar: 1.9,
        category: 'Vegetables' },
    { name: 'Green beans, boiled', kcal: 35, protein: 1.9, carbs: 7.9, fat: 0.3, fiber: 3.2, sugar: 1.5,
        category: 'Vegetables' },
    { name: 'Iceberg lettuce, raw', kcal: 14, protein: 0.9, carbs: 3.0, fat: 0.1, fiber: 1.2, sugar: 1.8,
        category: 'Vegetables' },
    { name: 'Rocket (arugula), raw', kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, sugar: 2.1,
        category: 'Vegetables' },
    { name: 'Radish, raw', kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, sugar: 1.9,
        category: 'Vegetables' },
    { name: 'Black beans, boiled', kcal: 132, protein: 8.9, carbs: 23.7, fat: 0.5, fiber: 8.7, sugar: 0.3,
        category: 'Vegetables' },
    { name: 'Olive oil', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0,
    category: 'Oils & Fats' },
    { name: 'Rapeseed oil', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0,
    category: 'Oils & Fats' },
    { name: 'Coconut oil', kcal: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0,
    category: 'Oils & Fats' },
    { name: 'Butter', kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sugar: 0.1,
    category: 'Oils & Fats' },
    { name: 'Margarine (70%)', kcal: 630, protein: 0.2, carbs: 0.2, fat: 70, fiber: 0, sugar: 0.2,
        category: 'Oils & Fats' },
    { name: 'Ghee', kcal: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, category: 'Oils & Fats' },
    { name: 'Ketchup (ICA)', kcal: 101, protein: 1.3, carbs: 23, fat: 0.2, fiber: 0.5, sugar: 21,
    category: 'Condiments' },
    { name: 'Mayo (full fat)', kcal: 717, protein: 1, carbs: 0.6, fat: 79, fiber: 0, sugar: 0.6,
        category: 'Condiments' },
    { name: 'Light mayo (ICA)', kcal: 260, protein: 0.8, carbs: 7, fat: 24, fiber: 0, sugar: 2,
        category: 'Condiments' },
    { name: 'Mustard (ICA)', kcal: 66, protein: 3.7, carbs: 6, fat: 3.1, fiber: 3.3, sugar: 0.5,
        category: 'Condiments' },
    { name: 'BBQ sauce (ICA)', kcal: 135, protein: 0.8, carbs: 33, fat: 0.3, fiber: 0.5, sugar: 28,
        category: 'Condiments' },
    { name: 'Soy sauce', kcal: 53, protein: 5, carbs: 5, fat: 0.1, fiber: 0.2, sugar: 0.5,
    category: 'Condiments' },
    { name: 'Pesto', kcal: 490, protein: 5, carbs: 6, fat: 47, fiber: 1.5, sugar: 1, category: 'Condiments' },
    { name: 'Tomato sauce', kcal: 42, protein: 1.5, carbs: 7, fat: 0.5, fiber: 1.5, sugar: 4,
    category: 'Condiments' },
    { name: 'Hot sauce', kcal: 20, protein: 0.5, carbs: 4, fat: 0, fiber: 0.5, sugar: 1,
    category: 'Condiments' },
    { name: 'Sugar, white', kcal: 387, protein: 0, carbs: 100, fat: 0, fiber: 0, sugar: 100,
    category: 'Sweeteners & Spices' },
    { name: 'Sugar, brown', kcal: 380, protein: 0, carbs: 98, fat: 0, fiber: 0, sugar: 95,
    category: 'Sweeteners & Spices' },
    { name: 'Honey', kcal: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, sugar: 82,
    category: 'Sweeteners & Spices' },
    { name: 'Maple syrup', kcal: 260, protein: 0, carbs: 67, fat: 0, fiber: 0, sugar: 60,
    category: 'Sweeteners & Spices' },
    { name: 'Cocoa powder', kcal: 228, protein: 20, carbs: 20, fat: 14, fiber: 33, sugar: 1,
    category: 'Sweeteners & Spices' },
    { name: 'Cinnamon', kcal: 247, protein: 4, carbs: 80, fat: 1.2, fiber: 53, sugar: 2,
    category: 'Sweeteners & Spices' },
    { name: 'ICA Basic, yogurt', kcal: 42, protein: 3.5, carbs: 4.8, fat: 0.5, fiber: 0, sugar: 4.8,
    category: 'ICA Specific' },
    { name: 'ICA Gott liv, müsli', kcal: 380, protein: 12, carbs: 60, fat: 8, fiber: 10, sugar: 15,
    category: 'ICA Specific' },
    { name: 'ICA Selection, olive oil', kcal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0,
    category: 'ICA Specific' },
    { name: 'ICA Basic, pasta', kcal: 365, protein: 13, carbs: 72, fat: 1.5, fiber: 3, sugar: 1,
    category: 'ICA Specific' },
    { name: 'ICA Gott liv, kvarg', kcal: 55, protein: 10, carbs: 3.5, fat: 0.2, fiber: 0, sugar: 3.5,
    category: 'ICA Specific' },
    { name: 'Coffee, brewed', kcal: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sugar: 0,
    category: 'Beverages' },
    { name: 'Tea, brewed', kcal: 1, protein: 0, carbs: 0.2, fat: 0, fiber: 0, sugar: 0.2,
    category: 'Beverages' },
    { name: 'Juice, orange', kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 8,
    category: 'Beverages' },
    { name: 'Juice, apple', kcal: 46, protein: 0.1, carbs: 11, fat: 0.1, fiber: 0.1, sugar: 10,
    category: 'Beverages' },
    { name: 'Smoothie (ICA)', kcal: 70, protein: 0.5, carbs: 16, fat: 0.5, fiber: 1, sugar: 12,
    category: 'Beverages' },
    { name: 'Tofu, raw', kcal: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sugar: 0.5,
    category: 'Other' },
    { name: 'Tofu, fried', kcal: 150, protein: 9, carbs: 3, fat: 12, fiber: 0.5, sugar: 0.5,
    category: 'Other' },
    { name: 'Seitan', kcal: 120, protein: 23, carbs: 5, fat: 1.5, fiber: 0.5, sugar: 0.5, category: 'Other' },
    { name: 'Nutritional yeast', kcal: 320, protein: 45, carbs: 35, fat: 5, fiber: 20, sugar: 1,
    category: 'Other' },
];

/* Emoji icons offered when picking an icon for a saved meal */
const MEAL_ICONS = [
    '🍳', '🥞', '🧇', '🥯', '🥣', '☕', '🍵', '🥛', '🧃', '🍽️',
    '🥗', '🍲', '🍛', '🍝', '🥘', '🍜', '🍣', '🥩', '🍗', '🥓',
    '🧀', '🍕', '🌮', '🌯', '🥙', '🧆', '🍔', '🌭', '🥨', '🍖',
    '🥪', '🍚', '🍤', '🥟', '🍠', '🍟', '🍿', '🍪', '🧁', '🍰',
    '🥧', '🍦', '🍩', '🍭', '🍬', '🍫', '🍮', '🍡', '🥜', '🌰',
    '🥤', '🍹', '🍺', '🍷', '🥂', '🥑'
];

/* Emoji icons offered when picking an icon for an ingredient category */
const CAT_ICON_OPTIONS = [
    // Meat
    '🥩', '🍖', '🍗', '🥓', '🌭', '🍔', '🦃', '🐔', '🐖', '🐄', '🐑',
    // Seafood
    '🐟', '🐠', '🐡', '🦐', '🦞', '🦀', '🐙', '🦑', '🐚', '🍣', '🍤', '🎣',
    // Dairy/eggs
    '🥚', '🍳', '🧀', '🥛', '🧈', '🍦',
    // Grains
    '🍞', '🥖', '🥐', '🥯', '🌾', '🍚', '🍜', '🍝', '🥣', '🥞', '🧇', '🌽',
    // Fruit
    '🍎', '🍏', '🍐', '🍊', '🍋', '🍌', '🍉', '🍇', '🍓', '🍈', '🍒', '🍑', '🥭', '🍍', '🥥', '🥝',
    // Veg
    '🥬', '🥦', '🥒', '🌶️', '🥕', '🧄', '🧅', '🥔', '🍠', '🍆', '🥑', '🍄', '🌱', '🌿', '☘️',
    // Nuts
    '🥜', '🌰',
    // Sweet
    '🍯', '🍬', '🍭', '🍫', '🍪', '🎂', '🧁', '🍰', '🥧', '🍩', '🍮', '🍨', '🍧', '🍡',
    // Drinks
    '🥤', '🧃', '☕', '🍵', '🥂', '🍷', '🍺', '🍹', '🧊', '💧', '🍶', '🧉',
    // Prepared
    '🍽️', '🥗', '🍲', '🍛', '🥘', '🍱', '🌮', '🌯', '🥙', '🧆', '🍕', '🥪', '🥟', '🍙', '🍘',
    // Other
    '📦', '🛒', '🧂', '🥄', '🍴', '🔥', '⭐', '❄️', '🏷️', '📋', '🧴', '📁'
];